---

- name: Install dependencies (apt)
  become: yes
  apt:
    name: [mysql-server, jq, maven]
    state: present
    update_cache: yes

- name: Install dependencies (pip)
  become: yes
  pip:
    name: [pymysql]

- name: Change root user password
  become: yes
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  ignore_errors: yes

- name: Ensure mysql running
  become: yes
  systemd: name=mysql state=started