- job:
    name: pipeline
    project-type: pipeline
    dsl: |
      node {
          stage('Source') {
              git 'https://github.com/chrisparnin/checkbox.io.git'
          }
          stage('Build') {
              sh 'ls /var/lib/jenkins/workspace/pipeline'
              sh 'npm install'
          }
          stage('Test') {
              sh 'npm test'
          }
      }