- job:
    name: pipeline
    project-type: pipeline
    dsl: |
      node {
          stage('Source') {
              git 'https://github.com/chrisparnin/checkbox.io.git'
          } 
          stage('Build') {
              sh 'pwd'
              sh 'npm cache clean'
              sh 'cd server-side/site && npm install'
          }
          stage('mongodb') {
              sh 'service mongod status'
          }
          stage('start server-side server') {
              sh 'cd server-side/site && node server.js &'
              sh "cd server-side/site && npm test"
          }
      }