---
- name: install python-pip
  apt:
    name: python-pip
    update_cache: yes
  become: yes

- name: install jq
  apt:
    name: jq
    update_cache: yes
  become: yes

- name: install nginx
  apt:
    name: nginx
    update_cache: yes
  become: yes

- name: Ensure nginx running
  systemd:
    name: nginx
    state: started
  become: yes

- name: apt update
  shell: sudo apt update

- name: Copy over file nginx config file
  copy:
    src: /bakerx/cm/default
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
    force: yes
    mode: u=rw,g=r,o=r
  become: yes

- name: Import the MongoDB public GPG Key
  become: yes
  shell: wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -

- name: Create a list file for MongoDB
  become: yes
  shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list

- name: Install mongodb
  apt:
    name: [mongodb-org]
    state: present
    update_cache: yes
  become: yes

- name: Install pymongo
  pip:
    name: pymongo
  become: yes

- name: Ensure mongodb running
  systemd:
    name: mongod
    state: started
  become: yes

- name: Create mongo root user and admin db
  become: yes
  mongodb_user:
    database: admin
    name: "{{ mongodb_admin_user }}"
    password: "{{ mongodb_admin_password }}"
    state: present
    roles: root

- name: Create mongo checkbox.io user and db
  become: yes
  mongodb_user:
    database: admin
    name: "{{ mongodb_app_user }}"
    password: "{{ mongodb_app_password }}"
    login_user: "{{ mongodb_admin_user }}"
    login_password: "{{ mongodb_admin_password }}"
    state: present
    roles:
      - { "db": "site", "role": "readWrite"}

- name: Populate /etc/environment
  become: yes
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value}}"
  no_log: true
  with_items:
    - key: APP_PORT
      value: 3002
    - key: MONGO_PORT
      value: 27017
    - key: MONGO_USER
      value: "{{ mongodb_app_user }}"
    - key: MONGO_PASSWORD
      value: "{{ mongodb_app_password }}"
    - key: MONGO_IP
      value: localhost

- name: Source the /etc/environment file
  shell: . /etc/environment

- name: Create checkbox.io server directory if it does not exist
  file:
    path: /home/vagrant/checkbox
    state: directory
    mode: '0755'

- name: Create checkbox.io .git directory if it does not exist
  file:
    path: /home/vagrant/checkbox/.git
    state: directory
    mode: '0755'

- name: initialize bare repo
  shell: git init --bare
  args:
    chdir: /home/vagrant/checkbox/.git

- name: Copy over file git hook file for forever reboots
  copy:
    src: /bakerx/cm/post-receive
    dest: /home/vagrant/checkbox/.git/hooks/post-receive
    owner: root
    group: root
    force: yes
    mode: u=rwx,g=x,o=x
  become: yes

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
  become: yes