---
- name: install dependencies (apt)
  apt:
    name: [python-pip, nodejs, npm, openjdk-8-jdk, jq]
    update_cache: yes
  become: yes

- name: Import the MongoDB public GPG Key 
  become: yes
  shell: wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -

- name: Create a list file for MongoDB
  become: yes
  shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list

- name: Install dependencies (apt)
  become: yes
  apt:
    name: [mongodb-org]
    state: present
    update_cache: yes

- name: Install dependencies (pip)
  become: yes
  pip:
    name: [pymongo]

- name: Ensure mongodb running
  become: yes
  systemd: 
    name: mongod
    state: started

- name: Create mongo root user and admin db
  become: yes
  mongodb_user:
    database: admin
    name: "{{ mongodb_admin_user }}"
    password: "{{ mongodb_admin_password }}"
    state: present
    roles: root

- name: Create mongo checkbox.io user and db
  become: yes
  mongodb_user:
    database: admin
    name: "{{ mongodb_app_user }}"
    password: "{{ mongodb_app_password }}"
    login_user: "{{ mongodb_admin_user }}"
    login_password: "{{ mongodb_admin_password }}"
    state: present
    roles: 
      - { "db": "site", "role": "readWrite"}

- name: Populate /etc/environment
  become: yes
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value}}"
  no_log: true
  with_items:
    - key: APP_PORT 
      value: 3002
    - key: MONGO_PORT 
      value: 27017
    - key: MONGO_USER 
      value: "{{ mongodb_app_user }}"
    - key: MONGO_PASSWORD 
      value: "{{ mongodb_app_password }}"
    - key: MONGO_IP 
      value: localhost

- name: Source the /etc/environment file
  shell: . /etc/environment
