- hosts: localhost
  tasks:
    - name: copy war file to local
      become: yes
      copy:
        src: /var/lib/jenkins/workspace/iTrust/iTrust2/target/iTrust2.war
        dest: /bakerx/cm/iTrust2.war
        remote_src: yes

- hosts: itrust
  vars_files:
    - creds.yml
  roles:
    - itrust-deploy

      
