---
# see the best practices in ansible docs for how to get started with creating roles etc.:
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html

- hosts: monitor
  vars_files:
      - creds.yml
  roles:
    - monitor
  # tasks:
  #   - name: Set env for checkbox and iTrust hosts
  #     debug:
  #       var: groups

- hosts: checkbox, itrust
  vars_files:
      - creds.yml
  roles:
    - agent
  # tasks:
  #   - name: Set env for checkbox and iTrust hosts
  #     debug:
  #       var: group_names

