---

- name: Add nodejs latest binary source
  shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -

- name: Install dependencies
  apt:
    name: [nodejs, redis-server, python-apt]
    update_cache: yes
  become: yes

- name: Modify redis conf file to enable remote connection with password authentication
  become: yes
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^requirepass', line: "requirepass {{ redis_password }}" }
    - { regexp: '^bind', line: "bind 0.0.0.0 ::1" }
  no_log: true

- name: Restart redis server
  systemd:
    state: restarted
    name: redis-server
  become: yes

- name: Install forever
  become: yes
  npm:
    name: forever
    global: yes
    state: present

- name: Stop all forever run jobs
  become: yes
  shell: forever stopall

- name: Install node dependencies
  become: yes
  npm: 
    path: "{{ item }}"
  with_items:
    - /bakerx/Monitoring/dashboard
    
- name: Forever run the dashboard
  become: yes
  shell: cd /bakerx/Monitoring/dashboard && forever start bin/www
  environment:
    HOST_BROKEN: "{{ groups.broken[0] }}"
    HOST_MASTER: "{{ groups.master[0] }}"
    REDIS_PASS: "{{ redis_password }}"
    PORT: 80

