---

- name: Add nodejs latest binary source
  shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -

- name: Install dependencies
  apt:
    name: [nodejs, redis-server, python-apt]
    update_cache: yes
  become: yes

- name: Install forever
  become: yes
  npm:
    name: forever
    global: yes
    state: present

- name: Create /agent with correct permissions
  become: yes
  file:
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    path: /agent
    state: directory
    mode: "0700"

- name: Synchronize agent (excluding node_modules)
  synchronize:
    src: /bakerx/Monitoring/agent/
    dest: /agent
    rsync_opts:
      - "--exclude=node_modules"

- name: Forever run the agent
  become: yes
  shell: "cd /agent && npm install && forever stopall && forever start index.js {{ group_names[0] }}"
  environment:
    HOST_MONITOR: "{{ groups.monitor[0] }}"
    REDIS_PASS: "{{ redis_password }}"