- name: Install python3-pip, python-apt
  become: yes
  apt:
    name: [python3-pip, python-apt]
    state: present
    update_cache: yes





- name: Install mysql-server and maven
  become: yes
  apt:
    name: [mysql-server, maven]
    state: present
    update_cache: yes

- name: Install pmysql
  become: yes
  pip:
    name: [pymysql]

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
  become: yes

- name: install JDK 11
  apt:
    name: openjdk-11-jdk
    state: present
  become: yes

- name: add tomcat group
  group:
    name: tomcat
  become: yes

- name: add tomcat user
  user:
    name: tomcat
    group: tomcat
    home: /user/share/tomcat
    createhome: no
  become: yes

- name: create /opt/tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    mode: 0755
  become: yes

- name: download & unarchive
  unarchive:
    src: https://downloads.apache.org/tomcat/tomcat-9/v9.0.37/bin/apache-tomcat-9.0.37.tar.gz
    dest: /opt/tomcat
    remote_src: yes
    extra_opts: [--strip-components=1]
  become: yes

- name: copy war file to iTrust server
  copy:
    src: /bakerx/cm/iTrust2.war
    dest: /opt/tomcat/webapps/iTrust2.war
    owner: vagrant
    group: vagrant
    force: yes
    mode: u=rwx,g=x,o=x
  become: yes
  
- name: Change ownership
  file:
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory
  become: yes

# - name: Copy Tomcat service from local to remote
  # copy:
    # src: tomcat.service
    # dest: /etc/systemd/system/
    # mode: 0755
  # become: yes /opt/tomcat/webapps

- name: Template the tomcat server config file
  template:
    src: tomcat
    dest: /etc/systemd/system/tomcat.service
    owner: tomcat
    mode: u=rwx,g=r,o=r
  become: yes

- name: Start and enable Tomcat service
  systemd:
    name: tomcat
    state: started
    enabled: true
    daemon_reload: true
  become: yes

- name: Change root mysql user password
  become: yes
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  ignore_errors: yes

- name: Ensure mysql running
  become: yes
  systemd: name=mysql state=started

- name: copy mysql database dump file to itrust
  copy:
    src: /bakerx/cm/itrust.sql
    dest: /home/vagrant/itrust.sql
    force: yes
  become: yes

- name: add iTrust2 database
  mysql_db:
    name: iTrust2
    state: import
    target: /home/vagrant/itrust.sql
    login_user: root
    login_password: "{{ mysql_root_password }}"